### ISSUE TITLE
[1.14.4] server crash forge

### ISSUE THREAD

**Issue by Sunekaer** [MrMarnic/AnimalNet#17] opened 2019-08-04 16:14 UTC
Server crash on launch 
forge:28.0.38
animalnet-v1.14.4 Forge b3.jar
https://paste.dimdev.org/elececejuf.rb

**Comment by MrMarnic** [comment] 2019-08-05 00:21
Did you change something in the config?

**Comment by MrMarnic** [comment] 2019-08-05 00:22
Can you post you config please

**Comment by Sunekaer** [comment] 2019-08-05 16:14
Default config
https://s1.sunekaer.com/files/animalnet-common.toml

**Comment by MrMarnic** [comment] 2019-08-11 11:42
Can you please tell me how you got the error. Because I can not reproduce it.
I think it has something to do with the config. Did you try to delete the animalnet config file?

**Comment by Sunekaer** [comment] 2019-08-11 11:48
Well, i downloaded forge server and copied all mods over and launched the server.
It generated config files it self

**Comment by MrMarnic** [comment] 2019-08-11 13:20
Does the mod work alone?

**Comment by MrMarnic** [comment] 2019-09-06 18:30
I am going to close this because of no further info

**Closed as completed** 2019-09-06 18:30 UTC
